"""
This code illustrates the use of Try and except blocks in python.
They are used for error exceptions
"""

# An example

try:
    print(x)
    # now this is an error because x is undefined. so when this occurs it moves on to the next block
except:
    print("An exception occurred: Define x")
